# Generated by Django 4.1.1 on 2022-09-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_remove_movie_director_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(to='movie_app.director'),
        ),
    ]
