# Generated by Django 4.1.1 on 2022-09-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0018_remove_movie_director_remove_movie_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='review',
            new_name='reviews',
        ),
    ]
