# Generated by Django 4.1.1 on 2022-09-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0019_rename_review_movie_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='movie_app.movie'),
        ),
    ]
