# Generated by Django 4.1.1 on 2022-09-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0020_review_movie_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_text',
            new_name='movie_title',
        ),
    ]
