# Generated by Django 4.1.1 on 2022-09-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0021_rename_movie_text_review_movie_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_title',
            new_name='movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='reviews',
        ),
    ]
