# Generated by Django 4.1.1 on 2022-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0022_rename_movie_title_review_movie_remove_movie_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='movie_app.review'),
        ),
    ]
