# Generated by Django 4.1.1 on 2022-09-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0023_remove_review_movie_movie_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(null=True, verbose_name=range(0, 5)),
        ),
    ]
