# Generated by Django 4.1.1 on 2022-09-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0027_alter_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='director_movies', to='movie_app.movie'),
        ),
    ]
