# Generated by Django 4.1.1 on 2022-09-28 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0032_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=1200), null=True),
        ),
    ]
