# Generated by Django 4.1.1 on 2022-09-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0036_alter_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
