# Generated by Django 4.1.1 on 2022-09-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0047_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
